version: '3.8'

services:
  wordpress:
    image: wordpress:fpm
    container_name: wordpress-solidarlink
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: mysql-wordpress-shared:3306
      WORDPRESS_DB_NAME: solidarlink_db
      WORDPRESS_DB_USER: solidarlink_user
      WORDPRESS_DB_PASSWORD: SolidarDB2025
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./wp-config-custom.php:/var/www/html/wp-config-custom.php
    user: "33:33"
    networks:
      - solidarlink-network
      - wordpress-shared-network
    labels:

  nginx:
    image: nginx:alpine
    container_name: nginx-solidarlink
    restart: "no"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wp-content:/var/www/html/wp-content:ro
    ports:
      - "9003:80"
    depends_on:
      - wordpress
    networks:
      - solidarlink-network
    labels:

networks:
  solidarlink-network:
    driver: bridge
  wordpress-shared-network:
    external: true
    name: wordpress-shared-network
