services:
  mysql-jesuishyperphagique:
    image: mysql:8.0
    container_name: mysql-jesuishyperphagique
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jesuishyperphagique_db
      MYSQL_USER: jesuishyperphagique_user
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-jesuishyperphagique-data:/var/lib/mysql
    networks:
      - jesuishyperphagique-network
    command: --default-authentication-plugin=mysql_native_password

  wordpress-jesuishyperphagique:
    image: wordpress:php8.3-fpm
    container_name: wordpress-jesuishyperphagique
    restart: unless-stopped
    user: "33:33"
    depends_on:
      - mysql-jesuishyperphagique
    environment:
      WORDPRESS_DB_HOST: mysql-jesuishyperphagique:3306
      WORDPRESS_DB_USER: jesuishyperphagique_user
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: jesuishyperphagique_db
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
    volumes:
      - wordpress-jesuishyperphagique-data:/var/www/html
    networks:
      - jesuishyperphagique-network

  nginx-jesuishyperphagique:
    image: nginx:alpine
    container_name: nginx-jesuishyperphagique
    restart: unless-stopped
    depends_on:
      - wordpress-jesuishyperphagique
    ports:
      - "9005:80"
    volumes:
      - wordpress-jesuishyperphagique-data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - jesuishyperphagique-network

networks:
  jesuishyperphagique-network:
    driver: bridge

volumes:
  mysql-jesuishyperphagique-data:
  wordpress-jesuishyperphagique-data:
